### ISSUE TITLE
Получение текста сообщения при использовании магазина за баллы

### ISSUE THREAD

**Issue by hodlbe** [rutony/rutonychat-testscripts#1]
Приветствую, как получить текст в удаленном управлении, когда отправляют за баллы что-то с текстом (как текст получить)? Если там только 2 параметра, имя и сумма баллов?

**Comment by rutony** [comment]
Там нет текста потому что он там нигде не используется.
Самый простой способ вытащить событие Твитч баллы это в автономных скриптах.
Там есть все нужное.

**Comment by hodlbe** [comment]
> Там нет текста потому что он там нигде не используется. Самый простой способ вытащить событие Твитч баллы это в автономных скриптах. Там есть все нужное.

![image](https://user-images.githubusercontent.com/23383285/154525243-ac777f60-5095-4f58-bbf4-06ac972c3fbf.png)
Ну здесь же можно указывать сообщения

**Comment by hodlbe** [comment]
конечно ещё хотелось бы получить оттуда и username

**Comment by rutony** [comment]
Повторюсь, в самом Удаленном управлении нигде не используется текст от Твитч баллов, поэтому там его может и не быть.
Актуальный способ получения этих данных через Автономные скрипты.

Плюс, само Удаленное управление доживает последние дни. Так как скоро стартует работа по полной переделке бота, удаленного управления и меток, на их замену прийдет один общий модуль, который позволит делать все что сейчас и даже больше в разы.
