### ISSUE TITLE
Добавить возможность указывать своё имя источника для внешних сообщений

### ISSUE THREAD

**Issue by erickskrauch** [rutony/rutonychat-testscripts#3]
Нужна возможность передавать своё имя сайта, с которого были взяты внешние сообщения, вместе с кастомной же иконкой.

**Comment by erickskrauch** [comment]
@rutony, а можно ссылку на обновлённую документацию или хотя бы так текстовое описание, как теперь это делать?

**Comment by rutony** [comment]
Такого функционала нет
